### ISSUE TITLE
Improve the issue template with an example

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/Pix#14]
Reading the issue template, it is not clear how the format should be. Should I write "what's happened", or it is just an hint for the content of the section? Which is the format of the title? Please note that the issue number is automatically generated.

Please add an example of a good issue.

**Comment by wbigger** [comment]
Consider also to use the [issue template](https://github.com/blog/2111-issue-and-pull-request-templates) feature on GitHub to automatically add the template in each new issue.

**Comment by matteogaldi** [comment]
Improved ISSUE_TEMPLATE.
Now it's the default template when you create a new Issue. Thanks for the advice! ;)
