### ISSUE TITLE
Clean-up repository files

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/Pix#15]
There are some files that probably should be removed.

- `.DS_Store`
- what is the purpose of `.package-lock.json` in the project root?

**Comment by matteogaldi** [comment]
As you recommended, we've cleaned up repo from useless files. Thank you!

**Comment by wbigger** [comment]
Another hint: if you have any .zip or similar compressed file that represent a specific snapshot of the project that you consider important, add it as 'Release' of the repository on GitHub.
